services:
  - type: web
    name: jotform-pdf-generator
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: PORT
        value: 10000
      - key: BASE_URL
        value: "https://jotform-pdf-generator.onrender.com/webhook"
      - key: ENABLE_EMAIL
        value: "false"
